import assert from 'node:assert/strict'
import { test } from 'node:test'

import { digestFileName, escapeLinkText, renderDigest } from '../lib/digest.js'
import type { FeedItem } from '../lib/types.js'

function item(overrides: Partial<FeedItem> = {}): FeedItem {
  return {
    id: 'x1',
    sourceId: 'src-1',
    title: 'A [weird] title `with` ticks',
    link: 'https://example.com/a(1)',
    summary: '',
    content: '',
    publishedAt: '2026-08-16T10:00:00.000Z',
    fetchedAt: '2026-08-17T08:00:00.000Z',
    hash: 'h',
    digestedDay: '',
    ...overrides,
  }
}

test('renderDigest produces a complete briefing in Chinese', () => {
  const md = renderDigest({
    date: '2026-08-17',
    language: 'zh',
    sourceTitles: new Map([['src-1', '示例源']]),
    items: [item()],
    summaryText: '这是摘要。',
    includeItemLinks: true,
  })
  assert.ok(md.startsWith('# RSS 简报 · 2026-08-17'))
  assert.ok(md.includes('> 1 条目 · 1 订阅源'))
  assert.ok(md.includes('## 综合摘要'))
  assert.ok(md.includes('这是摘要。'))
  assert.ok(md.includes('## 条目'))
  // Parens in the URL are percent-encoded so they cannot break the link.
  assert.ok(md.includes('[A \\[weird\\] title \\`with\\` ticks](https://example.com/a%281%29)'))
  assert.ok(md.includes('> 示例源 · 2026-08-16'))
  assert.ok(md.trimEnd().endsWith('Generated by dsh-rss-digest'))
})

test('renderDigest honors language and link toggling', () => {
  const md = renderDigest({
    date: '2026-08-17',
    language: 'en',
    sourceTitles: new Map([['src-1', 'Source One']]),
    items: [item()],
    summaryText: 'Summary here.',
    includeItemLinks: false,
  })
  assert.ok(md.startsWith('# RSS Daily Digest · 2026-08-17'))
  assert.ok(md.includes('## Summary'))
  assert.ok(md.includes('## Items'))
  assert.ok(!md.includes('[' + 'A'))
  assert.ok(md.includes('1. A \\[weird\\] title \\`with\\` ticks'))
})

test('renderDigest falls back to source id when no title is known', () => {
  const md = renderDigest({
    date: '2026-08-17',
    language: 'en',
    sourceTitles: new Map(),
    items: [item()],
    summaryText: '',
    includeItemLinks: true,
  })
  assert.ok(md.includes('src-1 · 2026-08-16'))
})

test('renderDigest neutralizes unsafe links from feeds', () => {
  const hostile = item({ link: 'javascript:alert(1) ) [click](javascript:alert(2)' })
  const md = renderDigest({
    date: '2026-08-17',
    language: 'en',
    sourceTitles: new Map(),
    items: [hostile],
    summaryText: '',
    includeItemLinks: true,
  })
  // The hostile URL must be rendered as plain text, never as a link target.
  assert.ok(!md.includes('](javascript:') && !md.includes('](http://') && !md.includes(']('))
})

test('escapeLinkText escapes link-text specials and collapses whitespace', () => {
  assert.equal(escapeLinkText('a [b] c `d`  e'), 'a \\[b\\] c \\`d\\` e')
})

test('digestFileName embeds the day and language', () => {
  assert.equal(digestFileName('2026-08-17', 'zh'), '2026-08-17-rss-briefing.md')
  assert.equal(digestFileName('2026-08-17', 'en'), '2026-08-17-rss-digest.md')
})