/**
 * Markdown rendering of a digest document.
 *
 * Pure module: turns digested items + a summary body into a complete Markdown
 * briefing. The summary body is produced by {@link summarize} (LLM or
 * extractive); this module is about the surrounding document.
 */

import type { DigestLanguage, FeedItem } from './types.js'

export interface DigestRenderOptions {
  /** Display date of the briefing (e.g. "2026-08-17"). */
  date: string
  language: DigestLanguage
  /** Map of sourceId → source title/label for provenance lines. */
  sourceTitles: ReadonlyMap<string, string>
  items: FeedItem[]
  /** The summary body (computed elsewhere). */
  summaryText: string
  /** Whether the item list embeds permalinks as Markdown links. */
  includeItemLinks: boolean
}

const LABELS: Record<DigestLanguage, { title: string; sources: string; items: string; generated: string }> = {
  zh: {
    title: 'RSS 简报',
    sources: '订阅源',
    items: '条目',
    generated: '生成于',
  },
  en: {
    title: 'RSS Daily Digest',
    sources: 'sources',
    items: 'items',
    generated: 'generated at',
  },
}

const SECTION_SUMMARY: Record<DigestLanguage, string> = { zh: '综合摘要', en: 'Summary' }
const SECTION_ITEMS: Record<DigestLanguage, string> = { zh: '条目', en: 'Items' }

/** Escape characters that are syntactically active inside Markdown link text. */
export function escapeLinkText(text: string): string {
  return text.replace(/[\[\]`]/g, (char) => `\\${char}`).replace(/\s+/g, ' ').trim()
}

/**
 * Sanitize a feed-supplied URL for embedding as a Markdown link target.
 * Only http(s) URLs are allowed; control characters are stripped and
 * whitespace/parens/backticks are percent-encoded so a hostile feed cannot
 * break out of the link or inject arbitrary Markdown.
 */
export function safeLinkUrl(link: string): string {
  const trimmed = (link ?? '').trim()
  if (!/^https?:\/\//i.test(trimmed)) return ''
  const cleaned = trimmed.replace(/[\u0000-\u001f\u007f]/g, '')
  return cleaned.replace(/[()\s`]/g, (char) => `%${char.charCodeAt(0).toString(16).padStart(2, '0')}`)
}

/** How old an item looks: publish date, falling back to fetch date. */
function itemDay(item: FeedItem): string {
  const from = item.publishedAt || item.fetchedAt
  return from.slice(0, 10)
}

/**
 * Render the complete briefing as one Markdown string. Items are expected to
 * be passed newest-first.
 */
export function renderDigest(options: DigestRenderOptions): string {
  const labels = LABELS[options.language]
  const sourceNames = new Set(options.items.map((item) => options.sourceTitles.get(item.sourceId) ?? item.sourceId))
  const header = [
    `# ${labels.title} · ${options.date}`,
    '',
    `> ${options.items.length} ${labels.items} · ${sourceNames.size} ${labels.sources} · `
      + `${labels.generated} ${options.date}`,
    '',
  ].join('\n')

  const summary = [
    `## ${SECTION_SUMMARY[options.language]}`,
    '',
    options.summaryText.trim() === '' ? '—' : options.summaryText,
    '',
  ].join('\n')

  const lines = options.items.map((item, index) => {
    const source = options.sourceTitles.get(item.sourceId) ?? item.sourceId
    const day = itemDay(item)
    const title = escapeLinkText(item.title)
    const link = options.includeItemLinks ? safeLinkUrl(item.link) : ''
    const head = link !== ''
      ? `${index + 1}. [${title}](${link})`
      : `${index + 1}. ${title}`
    const meta = [source, day].filter((part) => part !== '').join(' · ')
    return `${head}  \n    > ${meta}`
  })
  const section = [
    `## ${SECTION_ITEMS[options.language]}`,
    '',
    ...lines,
    '',
  ].join('\n')

  const footer = ['---', '', `Generated by dsh-rss-digest`, ''].join('\n')
  return `${header}\n${summary}\n${section}\n${footer}`
}

/** Default document header line, useful for file names and CLI output. */
export function digestFileName(date: string, language: DigestLanguage): string {
  const label = language === 'zh' ? 'rss-briefing' : 'rss-digest'
  return `${date}-${label}.md`
}